api_platform:
    #defaults:
        #pagination_enabled: false
    defaults:
        pagination_items_per_page: 50
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/ld+json']
    swagger:
        versions: [3]
