# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    #default_filter_set_settings:
        #format: webp

    resolvers:
        galerie_images_cache:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "img/indatabase/galerie/cache"

    loaders:
        galerie_content:
            filesystem:
                data_root: "%kernel.project_dir%/public/img/indatabase/galerie/content"
        galerie_cover:
            filesystem:
                data_root: "%kernel.project_dir%/public/img/indatabase/galerie/cover"

    filter_sets :
        cache: ~

        # Galerie
                        
        galerie_content_thumb: 
            cache: galerie_images_cache
            data_loader: galerie_content
            quality : 90
            filters:
                scale:
                    dim: [ 600, 800 ]
        galerie_cover_index_thumb:
            cache: galerie_images_cache
            data_loader: galerie_cover
            quality : 80
            filters:
                scale:
                    dim: [ 300, 200 ]
        galerie_cover_thumb:
            cache: galerie_images_cache
            data_loader: galerie_cover
            quality : 80
            filters:
                scale:
                    dim: [ 600, 300 ]
        galerie_title_edit:
            cache: galerie_images_cache
            data_loader: galerie_cover
            quality : 80
            filters:
                scale:
                    dim: [ 1000, 500 ]

