# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers :
        galerie_images_cache:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "img/indatabase/galerie/cache"

    filter_sets :
        cache: ~

        # Galerie
           
        galerie_thumb:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 550, 350 ]                 
        galerie_content_edit:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 600, 800 ]
        galerie_cover_index_thumb:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 300, 200 ]
        galerie_cover_edit:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 600, 300 ]
        galerie_title_edit:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 1000, 500 ]

