twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        google_recaptcha_v3_site_key: '%google_recaptcha_v3_site_key%'
        galerie_cover_path: '%galerie_cover_path%'
        galerie_content_path: '%galerie_content_path%'
        site_nom: '%site_nom%'

when@test:
    twig:
        strict_variables: true
