vich_uploader:
    db_driver: orm

    mappings:
        cover_image_galerie:
            uri_prefix: /img/indatabase/galerie/cover
            upload_destination: '%kernel.project_dir%/public/img/indatabase/galerie/cover'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
